name: Build, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  ECR_REGISTRY: your-aws-account.dkr.ecr.us-west-2.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build and tag Docker image
      id: build-image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ env.ECR_REGISTRY }}/my-app:${{ env.IMAGE_TAG }}

    - name: Run unit tests
      run: npm test

    - name: Push Docker image to ECR
      id: push-image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.ECR_REGISTRY }}/my-app:${{ env.IMAGE_TAG }}
      env:
        ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        AWS_REGION: ${{ env.AWS_REGION }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install Helm
      uses: helm/install@v1
      with:
        version: v3.6.3

    - name: Deploy to Kubernetes
      uses: helm/chart-testing-action@v2
      with:
        helm_chart_path: ./helm
        kubeconfig: ${{ secrets.KUBECONFIG }}
